version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@octokit/action"
        versions:
          - 3.2.3
          - 3.2.6
          - 3.3.1
          - 3.3.2
          - 3.4.0
          - 3.4.1
          - 3.7.1
          - 3.7.3
          - 3.8.0
      - dependency-name: "@actions/core"
        versions:
          - 1.2.7
      - dependency-name: husky
        versions:
          - 4.3.8
          - 5.0.9
          - 5.1.1
          - 5.2.0
          - 6.0.0
      - dependency-name: ws
        versions:
          - 7.4.2
      - dependency-name: lint-staged
        versions:
          - 10.5.3
