name: "Capture Vercel Preview URL"
author: "Aaron Imming <aaim@protonmail.com>"
description: "Capture a Vercel preview URL and feed it into your next GitHub action."
branding:
  icon: "triangle"
  color: "black"
inputs:
  cancel_on_strings:
    description: "Cancel the action when comment contains these words (comma separated list)"
    required: false
    default: "Deployment in progress,Preview: Failed"
  GITHUB_TOKEN:
    description: "GitHub actions token to cancel the action in case preview URL could not be found. If not specified, the action will explicitly fail."
    required: false
    default: ""
  preview_url_regexp:
    description: "Regular expression pattern to capture the preview URL. Ensure first capture group captures the preview URL."
    required: false
    default: '\[Visit Preview\]\((.*.sx)\)' # Do use single quotes, do NOT use delimiters.
  vercel_bot_name:
    description: "The name of the Vercel account commenting on pull requests."
    required: false
    default: "vercel[bot]"
outputs:
  vercel_preview_url:
    description: "The preview URL for the pull request's Vercel deployment."
runs:
  using: "node12"
  main: "dist/index.js"
